# This compose file is for Aiven Runtime

services:

  airflow-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Aiven Runtime deployment sets DATABASE_URL to the PG service
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${DATABASE_URL}
    depends_on:
      - airflow-pg-server
    ports:
      - "8080:8080"

  # Our Aiven for PostgreSQL service
  # Aiven Runtime deployment will sort out the actual environment variables for us
  airflow-pg:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
